.TH "main.hpp" 3 "Sat Feb 11 2017" "Rtree" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBNode< N, condition_type, default_cond >\fP"
.br
.RI "\fBmain\&.hpp\fP "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rtree from the source code\&.
